// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lewjdlxyyanmloxzohra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxld2pkbHh5eWFubWxveHpvaHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTUxMDQsImV4cCI6MjA1OTYzMTEwNH0.cVssOD85MlTm1Jjk-3aDMn97XbeHpAJmoobnzyH-tEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);